### PR TITLE
Issue 175 : Fix the Navbar and add hover effect

### PR DESCRIPTION
**Pull request by Utsavladia**
## Fixed the navbar on top so on scrolling the screen it stays at top.
Added hover effect to improve user experience.

Issue no.
#175 

image
Screenshot 2024-05-27 192303
 
Please review this and
Thank you for giving me this opprtunity. Looking forward  for more contributions.

### CODE REVIEW

**Comment by souravbhunia07** [comment]
@SamarthKadam have a look pr.

**Comment by Utsavladia** [comment]
@SamarthKadam  @souravbhunia07  Kindly review this PR

**Comment by Utsavladia** [comment]
@Spiral-Memory  @SamarthKadam 
Kindly review this PR before closing of GSSOC 🙂

**Comment by Spiral-Memory** [comment]
Hey @Utsavladia 

Could you please attach a video of before and after ?

**Comment by Utsavladia** [comment]
@Spiral-Memory 
## After
https://github.com/user-attachments/assets/20e8b513-c7e6-4512-a114-35da94ec0b4e


## Before
https://github.com/user-attachments/assets/4a40d0f8-3937-4ca6-b758-3c814b6809c1

**Comment by Spiral-Memory** [comment]
Hey @Utsavladia,

Could you please avoid reformatting the code? The changes you made to the formatting make it difficult to review. Kindly revert those formatting changes and push only the actual code modifications you made.

Also, this is a really annoying issue I faced with this repo. It would be great if we enforced a linting check with a specific format style and added it to the GitHub workflows. If you're interested, you can work on it as well. What's your thought on this @SamarthKadam

**Pull request closed without merging**
