### PR TITLE
add forget password feature #35

### PR DESCRIPTION
**Pull request by piyush-gangrade**
Addition:
1. ForgetPassword.jsx for enter an email to reset a password
2. ResetPassword.js for check token is valid or not and reset a password if token is valid.

Updates:

- AuthController.js
add 'sendForgetMail' funtion for generating temporary token and sent a mail .
add 'verifyForgetMail' function for checking token is valid or not.
add 'resetPassword' function for update password.

- backend/config.env

for sending mail:
MAIL_HOST=smtp.gmail.com
MAIL_PORT=465
MAIL_SECURE=true
MAIL_USER=yourEmail
MAIL_PASS=yourPass

#client url
BASE_URL=http://localhost:3000 

https://github.com/SamarthKadam/ChatBox/assets/133166222/b64ca2d1-58d6-4557-9faa-c1573dec6b20

### CODE REVIEW

**Comment by SamarthKadam** [comment]
@piyush-gangrade great work. Create a seprate branch and make pr

**Comment by piyush-gangrade** [comment]
@SamarthKadam  which try of error you got

**Comment by SamarthKadam** [comment]
I'll setup my environment and get back to you

**Comment by SamarthKadam** [comment]
I've added all the env files in the server. Anything I need to configure?

**Comment by piyush-gangrade** [comment]
No.

**Comment by SamarthKadam** [comment]
@piyush-gangrade There's some errors related to blocked cors

**Comment by piyush-gangrade** [comment]
If you want you can change it because no such error occurs on my system.

Screenshot_2024-05-15-12-08-48-60_40deb401b9ffe8e1df2f1cc5ba480b12

If error is still occurs than please provide screen video or screenshot for better understanding.

**Comment by piyush-gangrade** [comment]
@SamarthKadam If you still encounter an error, could you please send me a screenshot? This will help me resolve the issue so I can work on the other issue. Also, please add reviewers, assignees, and labels. Thank you!

**Comment by SamarthKadam** [comment]
@piyush-gangrade I'll try and let you know

**Pull request closed without merging**
