### PR TITLE
Added separate modals for alerts and confirmations

### PR DESCRIPTION
**Pull request by anusha7530**
I have added separate modals for alerts and confirmations. Kindly review it. #162

### CODE REVIEW

**Comment by SamarthKadam** [comment]
@anusha7530 Change the design of the modal. Keep it synchronized with the background

**Comment by anusha7530** [comment]
> @anusha7530 Change the design of the modal. Keep it synchronized with the background

I have made changes to the design to synchronize with the bg. Kindly review it!

**Comment by anusha7530** [comment]
@SamarthKadam  Have you reviewed this?

**Comment by anusha7530** [comment]
> @anusha7530 Change the design of the modal. Keep it synchronized with the background

@SamarthKadam Have you reviewed it again? Any further updates..

**Comment by anusha7530** [comment]
> @anusha7530 Change the design of the modal. Keep it synchronized with the background

@SamarthKadam Have you reviewed it? Any further updates?

**Pull request closed without merging**
