### PR TITLE
Added a responsive Footer

### LINKED ISSUE #25: Footer can be added
Footer can be added. Signup page is not working . Its ui can be improved.

### PR DESCRIPTION
**Pull request by deepak9285**
FIXED  #25 
Added the responsive footer in the homepage.
I have made one new folder of footer inside fronted/src/components/HomeComponents
Folder footer contains Footer.css and Footer.js file
photo_2024-05-12_19-21-00

### CODE REVIEW

**Comment by SamarthKadam** [comment]
@deepak9285 create a seperate branch and push it

**Comment by SamarthKadam** [comment]
@deepak9285 keep it simple that looks too fancy and create a different branch

**Comment by deepak9285** [comment]
> @deepak9285 keep it simple that looks too fancy and create a different branch

okk sir

**Comment by deepak9285** [comment]
> Owner

I have changed the branch .

**Comment by SamarthKadam** [comment]
@deepak9285 I've gone throught it. But stil the links are not valid as they lead to nowhere. Btw great work

**Comment by deepak9285** [comment]
sur but i don't have any social media links i have mad just structure

**Comment by deepak9285** [comment]
i thought i have to make only structure

**Pull request closed without merging**
