### PR TITLE
Added auto comment on PR

### LINKED ISSUE #275: Automatic Comment on Pull Request Raised
Often, when pull requests (PRs) are raised, reviewers may lack crucial context about the changes proposed. This can lead to delays in the review process and misunderstandings between contributors and reviewers.

### PR DESCRIPTION
**Pull request by thevijayshankersharma**
fixes #275 

we are implementing an automated comment feature for PRs. Upon raising a PR, this feature will automatically append a standardized comment to provide essential context about the changes.

### CODE REVIEW

**Comment by SamarthKadam** [comment]
@thevijayshankersharma  we will review it soon. you can star our project till then

**Comment by Spiral-Memory** [comment]
Hey @thevijayshankersharma 

Could you please add a recorded video in the PR description that the functionality works.

Replicate the functionality in your forked repo, record a video and share it here. 

Thanks !

**Review by Spiral-Memory — APPROVED** [review]
LGTM!

**Comment by Spiral-Memory** [comment]
Once the functionality is verified through the video demonstration.. it will be ready to merge !

**Comment by thevijayshankersharma** [comment]
> Once the functionality is verified through the video demonstration.. it will be ready to merge !

I can't record the video for it. once got got merge, and the is PR is raised then the functionality will be visible.

**Comment by thevijayshankersharma** [comment]
@SamarthKadam  @Spiral-Memory could you add labels to it.

**Pull request merged**
