### PR TITLE
ALERT ADDED

### PR DESCRIPTION
**Pull request by Ansh101112**
## Description
Add confirmation alert before uploading image and alert after successful upload.

## Issue Number 
#5 

## Changes Made
- Modified the handleUpload function to include confirmation alert before uploading.
- Added alert after successful upload.
- Added alert to remind user to select an image if none is selected.

## Screenshots:
Screenshot (56)

another confirmation added for image uploading: 
Screenshot (57)

## Checklist:
- [x] Tested locally and confirmed functionality.
- [ ] Added relevant documentation.
- [ ] Reviewed and addressed any linting errors.
- [ ] Checked for any potential performance issues.
- [ ] Ensured compatibility with all supported browsers.
- [ ] All tests passed.

## Related Issues
#22 

## Note
This is the GSSOC'24 PR

### CODE REVIEW

**Comment by Ansh101112** [comment]
@SamarthKadam please see the authorisation error coming up here.

**Comment by SamarthKadam** [comment]
@Ansh101112 Try to push the complete file backend + frontend

**Comment by Ansh101112** [comment]
@SamarthKadam sir it is there I have pushed the both frontend and backend folder

**Comment by Ansh101112** [comment]
@SamarthKadam please see now

**Comment by Ansh101112** [comment]
@SamarthKadam sir please add the gssoc and level badge to this pr

**Comment by Ansh101112** [comment]
@SamarthKadam sir please add gssoc and level badge to my pr

**Pull request merged**
