### PR TITLE
fixed login signup page

### PR DESCRIPTION
**Pull request by Ketanop321**
issue no:- #287 

The problem was that login and signup box container box was not visible , some part of top and bottom were hidden behind.And this is happenning is happening in my 14 inch laptop which is small laptop compare to other laptop , but now it will be visible.
Before fixing the issue⤵️

https://github.com/SamarthKadam/ChatBox/assets/146806880/d359eef4-28f3-4d2a-8d2f-05b43ef9e260

after fixing the issue⤵️

https://github.com/SamarthKadam/ChatBox/assets/146806880/452d488d-8a27-4fdd-916d-8098248f8d4f

### CODE REVIEW

**Comment by SamarthKadam** [comment]
@Ketanop321 You have to fix the screen issue right. I see there is change in design as well.Im not able to see box shadow.

**Comment by Ketanop321** [comment]
@SamarthKadam  can you check again i have made some changes again

**Comment by Ketanop321** [comment]
@SamarthKadam

**Comment by Spiral-Memory** [comment]
Hey @Ketanop321 

You have only made changes to the `div` className in both pages, right? Or is there anything else?

```
<div className='flex flex-col items-center h-[100vh] w-[100vw] relative overflow-hidden px-2'>
```

It's difficult to review. Can you please highlight the code changes you made? Also, could you please run a formatter (maybe Prettier)?

**Pull request closed without merging**
