### PR TITLE
Mic icon fixed, added mic on/off sound, added feature to deactivate M…

### PR DESCRIPTION
**Pull request by mondalsurojit**
📌 Mic icon fixed
📌 Added mic on/off sound
📌 Added feature to deactivate Mic after 5 seconds of inactivity

@SamarthKadam please review it. It took some effort to solve, and I hope you will consider marking it as a level-2 gssoc problem atleast. Thank you in advance.

https://github.com/SamarthKadam/ChatBox/assets/114282267/2f71b0bc-1d7c-407a-8295-db5f5858ab07

### CODE REVIEW

**Comment by SamarthKadam** [comment]
@mondalsurojit great work but look for the alignment of cancel button it appears to be distored in means of design. Fix it

**Comment by mondalsurojit** [comment]
@SamarthKadam Sir, can you please share a screenshot, so that I can understand the problem in details. Actually, on my pc (maybe for my laptop size), its working fine.

**Comment by mondalsurojit** [comment]
@SamarthKadam Sir, please check once, whether its okay or not...

**Comment by SamarthKadam** [comment]
@mondalsurojit pull the latest fork and make pr

**Comment by mondalsurojit** [comment]
@SamarthKadam I did what you said...

**Comment by SamarthKadam** [comment]
@mondalsurojit please create a different branch and make pr

**Comment by mondalsurojit** [comment]
@SamarthKadam So, sir is it merged?

**Comment by SamarthKadam** [comment]
@mondalsurojit Please make a pr with creating different branch

**Comment by SamarthKadam** [comment]
@mondalsurojit please make the above changes

**Pull request closed without merging**
