### PR TITLE
 Add hover color in header 

### LINKED ISSUE #249: Bug: Add hover text in header
image
Kindly assign me this issue

### PR DESCRIPTION
**Pull request by AkhilaSunesh**
https://github.com/SamarthKadam/ChatBox/assets/140897461/96dd4f1f-184a-4c10-8c89-ca6ffc69f594

fixes #249 
Hover text is not needed as the text is crystal clear.
I have added hover color.

### CODE REVIEW

**Comment by SamarthKadam** [comment]
@AkhilaSunesh  No need of underline

**Comment by AkhilaSunesh** [comment]
done

**Comment by SamarthKadam** [comment]
@AkhilaSunesh bro look at the preview once. Its seems like design broke

**Comment by AkhilaSunesh** [comment]
I have raised another pr. pls check

**Comment by SamarthKadam** [comment]
@AkhilaSunesh bro  look at the design why is that option tab coming in?

**Comment by AkhilaSunesh** [comment]
Could you please send a screenshot? I haven't understood. Moreover I have raised another PR but you have closed it.

**Pull request closed without merging**
