### PR TITLE
Fixes empty message issue

### PR DESCRIPTION
**Pull request by Ansh101112**
## Description
Fixes the empty message sending by user.

## Changes Made
- Added state `alertShown` to track if the alert has been shown.
- Modified `sendMessage` function to check if the alert has been shown and if the message is empty before sending the message.
- Updated the code to ensure that the error message only appears once, and subsequent message attempts are not blocked after dismissing the alert.

## How to Test
1. Start the application.
2. Go to the messaging feature.
3. Attempt to send an empty message.
4. Verify that an alert appears indicating that the message cannot be empty.
5. Dismiss the alert.
6. Attempt to send a message again.
7. Verify that the message is sent without any error messages appearing.

## Screenshots:
Screenshot (62)

## Issue Solved
#22 

## NOTE
This is the PR under GSSOC'24

### CODE REVIEW

**Comment by Ansh101112** [comment]
@SamarthKadam sir please see the PR and authorize it asap.

**Comment by SamarthKadam** [comment]
@Ansh101112  Try to use toast message to show it. not the the alert window. I've used toastify package over it you can make use of it

**Comment by Ansh101112** [comment]
@SamarthKadam okay will do

**Comment by Ansh101112** [comment]
@SamarthKadam sir i have used the states as it is gennerating a bug as the user have seen the alert and start typing the message it is generating a alert again before typing so to fix this i have used the state.

**Review by Ansh101112 — COMMENTED** [review]
Screenshot (64)
@SamarthKadam sir added the toast alert now and fix other minor issues

**Comment by SamarthKadam** [comment]
@Ansh101112 there some bug. If I space first then it gives me propt saying messages can't be empty

**Comment by Ansh101112** [comment]
> @Ansh101112 there some bug. If I space first then it gives me propt saying messages can't be empty. And Im seeing empty messages sent

Okay sir fixing that bug now.

**Review by Ansh101112 — COMMENTED** [review]
Fixed the bug of spacing alert error coming up @SamarthKadam please see now sir.

**Comment by SamarthKadam** [comment]
@Ansh101112 fork the recent repo its been updated

**Comment by Ansh101112** [comment]
> @Ansh101112 fork the recent repo its been updated

Okay sir will do and push again 👍

**Comment by Ansh101112** [comment]
@SamarthKadam sir please see now as the new ui has been fixed and pushed.

**Comment by SamarthKadam** [comment]
@Ansh101112 3 prompts are been shown. It should be shown only once

**Comment by Ansh101112** [comment]
> @Ansh101112 3 prompts are been shown. It should be shown only once

Sir please try again as there must be a minor glitch in your system as I have tested the feature many times it doesn't shows 3 alerts.

**Comment by SamarthKadam** [comment]
@Ansh101112 try to send empty message. Once you get the prompts. Try to cancel the prompts. you wil see it

**Comment by Ansh101112** [comment]
> @Ansh101112 try to send empty message. Once you get the prompts. Try to cancel the prompts. you wil see it

Okay sir will fix this bug.

**Comment by Ansh101112** [comment]
@SamarthKadam sir I tried very well to fix that 3 times error bug but reduced it to 2 its maybe some error due to their internal docs code error that is conflicting with other installed library as searched on internet. Sir if you allowed I can add the normal JS alert inplace of this.

**Comment by Ansh101112** [comment]
@SamarthKadam sir what to do any update?

**Pull request closed without merging**
