### PR TITLE
Added Navigation Link to the Website Logo

### PR DESCRIPTION
**Pull request by MastanSayyad**
I have Fixed the issue #92 

Added Navigation Link to the Website Logo/Title 

image

@Saigenix, @SamarthKadam Please take a look and review it.

### CODE REVIEW

**Comment by Saigenix** [comment]
Good work! We will review and merge soon

**Comment by MastanSayyad** [comment]
Hey @SamarthKadam could you please tell me why you close the PR without merging it.

**Comment by SamarthKadam** [comment]
@MastanSayyad  Well it didn't many sense to me

**Comment by MastanSayyad** [comment]
@SamarthKadam yeah you're right as of now due to lack of contents in homepage and navbar is not fix when scroll down. I raised this minor issue bcoz it is a very common practice to link the homepage to the site title/logo...in future after adding more contents to the front page and fixing the navbar it will make sense.

**Comment by Saigenix** [comment]
> @MastanSayyad Well it didn't many sense to me

It's small change but mostly all website have this feature that that's why I suggested him to work. I think @MastanSayyad should add some more fixes and content Then it should be good to merge

**Pull request closed without merging**
