### PR TITLE
Mic icon fixed, added mic on/off sound, added feature to deactivate M…

### PR DESCRIPTION
**Pull request by mondalsurojit**
📌 Mic icon fixed
📌 Added mic on/off sound
📌 Added feature to deactivate Mic after 5 seconds of inactivity

@SamarthKadam please review it. It took some effort to solve, and I hope you will consider marking it as a level-2 gssoc problem atleast. Thank you in advance.

https://github.com/SamarthKadam/ChatBox/assets/114282267/2f71b0bc-1d7c-407a-8295-db5f5858ab07

### CODE REVIEW

**Comment by SamarthKadam** [comment]
@mondalsurojit when I try to upload the image I get some errors  shown by vercel regarding

**Comment by SamarthKadam** [comment]
@mondalsurojit when I try to upload the image I get some errors shown by vercel regarding
Screenshot (586)

**Comment by mondalsurojit** [comment]
@SamarthKadam I have no idea whats this...do you know, how to get over this error...please help...

**Comment by SamarthKadam** [comment]
@mondalsurojit im also able to not figure it out. Listen make a anothe fork and add your funtionality code and make pr. For now im closing this pr

**Pull request closed without merging**
