### PR TITLE
adding online status indicator feature

### LINKED ISSUE #173: Add User Online Status Indicator
# Issue Description
Currently, users have no way of knowing who is online within the application. Adding an online status indicator will enhance the user experience by allowing users to see which other users are currently active.

# Task
Implement an online status indicator (e.g., a green dot) next to the usernames or profile pictures to show who is currently online.
Ensure that the online status updates in real-time as users log in and out.
Display the online status in relevant sections of the application, such as the user list or chat interface.
Expected Outcome
Users should be able to see an online status indicator next to other users who are currently active. This will enhance the interactivity and social aspect of the application by providing real-time information on user activity.

# Notes
Ensure that the online status indicator is visually consistent with the existing UI design.
The online status should be updated in real-time and be reliable.
Consider using WebSockets or similar technology to handle real-time updates.

# Labels and Assignment
If you consider this a valid issue, please add the appropriate label indicating the level of the issue and assign it to me.

### PR DESCRIPTION
**Pull request by aakashsharma003**
# Demo Video
A demonstration video showcasing the updates can be viewed

https://github.com/SamarthKadam/ChatBox/assets/122847899/b241f0e1-0589-4e73-855e-da4d71a6b0c3

# Related Issue
- Fixes #173 

# Review Notes
Please review this PR and suggest any additional improvements or changes that could further enhance the application. Your feedback is valuable and appreciated.

### CODE REVIEW

**Comment by SamarthKadam** [comment]
@aakashsharma003 We don't need last seen text. Just add the green dot beside the profile pic that's enough
Screenshot (592)

**Comment by aakashsharma003** [comment]
Cool, here is the updated one !
 Is it meet requirements ?

https://github.com/SamarthKadam/ChatBox/assets/122847899/a2ab61e5-c9a6-4604-901b-700f25fb159f

**Comment by aakashsharma003** [comment]
Hi @SamarthKadam, I wanted to let you know that some changes are due to the Code Prettier extension in VSCode. Hopefully, this will help you in reviewing the code.

**Comment by aakashsharma003** [comment]
@SamarthKadam, have you finished the review?

**Comment by aakashsharma003** [comment]
@SamarthKadam , any update?

**Comment by aakashsharma003** [comment]
@SamarthKadam, Is it not being a long review?

**Comment by SamarthKadam** [comment]
@aakashsharma003  Pull the latest fork and make a pr

**Comment by aakashsharma003** [comment]
Okay @SamarthKadam

**Comment by aakashsharma003** [comment]
@SamarthKadam, Submitted PR #240 as discussed, following your pull latest, commit changes.

**Pull request closed without merging**
